FROM ubuntu:18.04

########################################
# Docker image name
#DB DOCKER_IMAGE_NAME=example1_nested3

# Docker build defined args
#DB DOCKER_BUILD_ARGS=

########################################

# [DO NOT REMOVE THIS LINE. THIS LINE WILL BE REMPLACED WITH GENERATED CODE]

